name: Push
on:  
  push:
    branches:
      - main
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: Install
        run: npm i -g codecov && npm i

      - name: Type checking
        run: npm run flow

      - name: Linter
        run: npm run lint

      - name: Testing
        run: npm run test

      - name: Coverage
        run: codecov

      - name: Building and Deploying to github page
        run: npm run build-storybook && npm run deploy
        
      - name: Building and deploying to npm
        run: npm run build && npm publish

      
      
      
      
